[package]
name = "diagnostics"
version.workspace = true
edition.workspace = true

[dependencies]
db_utils = { path = "../db_utils" }
filesystem = { path = "../filesystem" }
itertools.workspace = true
salsa.workspace = true

[dev-dependencies]
diagnostics_proc_macros = { path = "../diagnostics_proc_macros" }
env_logger.workspace = true
indoc.workspace = true
pretty_assertions.workspace = true
test-log.workspace = true
