[package]
name = "debug"
version.workspace = true
edition.workspace = true

[dev-dependencies]
db_utils = { path = "../db_utils" }
diagnostics_proc_macros = { path = "../diagnostics_proc_macros" }
env_logger.workspace = true
salsa.workspace = true
test-log.workspace = true
